name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  actions: read
  checks: write
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - id: setup
      name: setup
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pip install setuptools pytest flake8 pep8-naming
          flake8-docstrings numpy
        max-score: null
        setup-command: python3 -m venv venv
        test-name: setup
        timeout: 1
    - id: package-install
      name: package-install
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pip install -e .
        max-score: null
        setup-command: venv/bin/python -m pip install -U pip
        test-name: package-install
        timeout: 1
    - id: exercise-6-1
      name: exercise-6-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pytest tests/test_exercise_6_1.py
        max-score: 1
        setup-command: ''
        test-name: exercise-6-1
        timeout: 1
    - id: exercise-6-2
      name: exercise-6-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pytest tests/test_exercise_6_2.py
        max-score: 1
        setup-command: ''
        test-name: exercise-6-2
        timeout: 1
    - id: exercise-6-3
      name: exercise-6-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pytest tests/test_exercise_6_3.py
        max-score: 1
        setup-command: ''
        test-name: exercise-6-3
        timeout: 1
    - id: flake8-test
      name: flake8-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m flake8 nonlinear_solvers/
        max-score: 1
        setup-command: ''
        test-name: flake8-test
        timeout: 1
    - env:
        EXERCISE-6-1_RESULTS: ${{steps.exercise-6-1.outputs.result}}
        EXERCISE-6-2_RESULTS: ${{steps.exercise-6-2.outputs.result}}
        EXERCISE-6-3_RESULTS: ${{steps.exercise-6-3.outputs.result}}
        FLAKE8-TEST_RESULTS: ${{steps.flake8-test.outputs.result}}
        PACKAGE-INSTALL_RESULTS: ${{steps.package-install.outputs.result}}
        SETUP_RESULTS: ${{steps.setup.outputs.result}}
      name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      with:
        runners: setup, package-install, exercise-6-1, exercise-6-2, exercise-6-3,
          flake8-test
